# Generated by Django 3.1.4 on 2021-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_remove_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
